E health management system/E health management system/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BOL;
using DAL;

namespace E_health_management_system.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            if (AdminDAL.ValidateUser(username, password))
            {
                TempData["username"] = username;
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Invalid Username OR Password");
                return View();
            }
        }
    }
}

E health management system/E health management system/Controllers/LaboratoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BOL;
using DAL;

namespace E_Health.Controllers
{
    public class LaboratoryController : Controller
    {
        // GET: LaboratoryRegistration
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            if (LaboratoryDAL.ValidateUser(username,password))
            {
                TempData["username"] = username;
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Invalid Username OR Password");
                return View();
            }
        }

        [HttpGet]
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post()
        {    // Retrieve form data using form collection 
            Laboratory laboratory = new Laboratory();

            TryUpdateModel(laboratory);
            if (ModelState.IsValid)
            {
                if (LaboratoryDAL.Insert(laboratory))
                {
                    return RedirectToAction("Login");
                }
                else
                {
                    ModelState.AddModelError("", "Username already exists");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult Details(string firstName, string lastName)
        {
            TempData["pfirstname"] = firstName;
            TempData["plastname"] = lastName;
            if (ModelState.IsValid)
            {
                List<Prescription> prescriptions = new List<Prescription>();
                prescriptions = PrescriptionDAL.GetPrescriptions(firstName, lastName);
                return View(prescriptions);
            }
            else
            {
                ModelState.AddModelError("", "Enter valid Patient Name..!!");
                return View();
            }
        }
    }
}

E health management system/E health management system/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BOL;
using DAL;

namespace E_Health.Controllers
{
    public class PatientController : Controller
    {
        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            if (PatientDAL.ValidateUser(username,password))
            {
                TempData["username"] = username;
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Invalid Username OR Password");
                return View();
            }
        }
        
        // GET: Patient/Create
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            return View();
        }

        // POST: Patient/Create
        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post(FormCollection collection)
        {
            Patient patient = new Patient();

            TryUpdateModel(patient);
            if (ModelState.IsValid)
            {
                if (PatientDAL.Insert(patient))
                {
                    return RedirectToAction("Login");
                }
                else
                {
                    ModelState.AddModelError("", "Username already exists");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        public ActionResult SearchDoctor()
        {
            return View();
        }

        public ActionResult ListDoctors(string specialization)
        {
            if (ModelState.IsValid)
            {
                List<Doctor> doctorList = new List<Doctor>();
                doctorList = DoctorDAL.GetAll(specialization);
                return View(doctorList);
            }
            else
            {
                ModelState.AddModelError("", "Select Specialization");
                return View();
            }
        }

        // GET: Patient/Details/5
        public ActionResult Details()
        {
            string dfirstname = TempData["dfirstname"].ToString();
            TempData.Keep();
            string dlastname = TempData["dlastname"].ToString();
            TempData.Keep();
            Doctor doctor = DoctorDAL.Get(dfirstname,dlastname);
            return View(doctor);
        }
        // GET: Patient/BookAppointment 
        [HttpGet]
        [ActionName("BookAppointment")]
        public ActionResult BookAppointment_Get()
        {
            return View();
        }
        
        [HttpPost]
        [ActionName("BookAppointment")]
        public ActionResult BookAppointment_Post(FormCollection collection)
        {
            Appointment appointment = new Appointment();
            appointment.Pusername = TempData["username"].ToString();
            TempData.Keep();
            appointment.Dfirstname = TempData["drfirstname"].ToString();
            TempData.Keep();
            appointment.Dlastname = TempData["drlastname"].ToString();
            TempData.Keep();

            TryUpdateModel(appointment);
            if (ModelState.IsValid)
            {
                appointment.Dinfoid = 0;
                appointment.Pinfoid = 0;
                appointment.Status = 0;
                AppointmentDAL.BookAppointment(appointment);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult History()
        {
            string username = TempData["username"].ToString();
            TempData.Keep();
            List<Appointment> history = new List<Appointment>();
            history = AppointmentDAL.History(username);
            return View(history);
        }

        [HttpGet]
        [ActionName("Feedback")]
        public ActionResult Feedback_Get()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Feedback")]
        public ActionResult Feedback_Post(FormCollection collection)
        {
            Feedback feedback = new Feedback();
            feedback.Pusername = TempData["username"].ToString();
            TempData.Keep();
            feedback.Dfirstname = TempData["fdfirstname"].ToString();
            TempData.Keep();
            feedback.Dlastname = TempData["fdlastname"].ToString();
            TempData.Keep();

            TryUpdateModel(feedback);
            if (ModelState.IsValid)
            {
                feedback.Dinfoid = 0;
                feedback.Pinfoid = 0;
                FeedbackDAL.Feedback(feedback);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
    }
}

E health management system/E health management system/Controllers/PharmacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BOL;
using DAL;

namespace E_Health.Controllers
{
    public class PharmacyController : Controller
    {
        // GET: PharmacyRegistration
        public ActionResult Index()
        {
            return View();
        }

        // GET: PharmacyRegistration/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            if (PharmacyDAL.ValidateUser(username,password))
            {
                TempData["username"] = username;
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Invalid Username OR Password");
                return View();
            }
        }

        public ActionResult PatientPrescription()
        {
            List<Prescription> prescriptions = new List<Prescription>();
            prescriptions = PharmacyDAL.GetAll();
            return View(prescriptions);
        }

        [HttpGet]
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post()
        {    // Retrieve form data using form collection 
            Pharmacy pharmacy = new Pharmacy();

            TryUpdateModel(pharmacy);
            if (ModelState.IsValid)
            {
                if (PharmacyDAL.Insert(pharmacy))
                {
                    return RedirectToAction("Login");
                }
                else
                {
                    ModelState.AddModelError("", "Username already exists");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult Details(string firstName, string lastName)
        {
            TempData["pfirstname"] = firstName;
            TempData["plastname"] = lastName;
            if (ModelState.IsValid)
            {
                List<Prescription> prescriptions = new List<Prescription>();
                prescriptions = PrescriptionDAL.GetPrescriptions(firstName, lastName);
                return View(prescriptions);
            }
            else
            {
                ModelState.AddModelError("", "Enter valid Patient Name..!!");
                return View();
            }
        }
    }
}

E health management system/E health management system/Views/Shared/_HealthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>E Health Management System</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="~/Content/images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/Content/images/apple-touch-icon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")

</head>

<body>
    <!-- Start header -->
    <header class="top-navbar">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index","Home")">
                    <img src="" alt="" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div style="padding-right:40px" collapse navbar-collapse" id="navbars-rs-food">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="@Url.Action("Index","Home")">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="@Url.Action("About","Home")">About Us</a></li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Regsitration</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown-a">
                                <a class="dropdown-item" href="@Url.Action("Create","Doctor")">Doctor</a>
                                <a class="dropdown-item" href="@Url.Action("Create","Patient")">Patient</a>
                                <a class="dropdown-item" href="@Url.Action("Create","Pharmacy")">Pharmacy</a>
                                <a class="dropdown-item" href="@Url.Action("Create","Laboratory")">Laboratory</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Login</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown-a">
                                <a class="dropdown-item" href="@Url.Action("Login","Admin")">Admin</a>
                                <a class="dropdown-item" href="@Url.Action("Login","Doctor")">Doctor</a>
                                <a class="dropdown-item" href="@Url.Action("Login","Patient")">Patient</a>
                                <a class="dropdown-item" href="@Url.Action("Login","Pharmacy")">Pharmacy</a>
                                <a class="dropdown-item" href="@Url.Action("Login","Laboratory")">Laboratory</a>

                            </div>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="@Url.Action("Contact","Home")">Help Desk</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- End header -->



    @RenderBody()
   




    <!-- Start Footer -->
    <footer class="footer-area bg-f">
        <div class="container" style="padding-top:100px">
        </div>

        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="company-name">
                            All Rights Reserved. &copy; 2020 <a href="#">E Health Management System</a> Design By :
                            <a href="https://html.design/">KauSan Technologies</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <!-- End Footer -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

   @Scripts.Render("~/Content/js")


    <!-- ALL PLUGINS -->
    <script src="js/jquery.superslides.min.js"></script>
    <script src="js/images-loded.min.js"></script>
    <script src="js/isotope.min.js"></script>
    <script src="js/baguetteBox.min.js"></script>
    <script src="js/form-validator.min.js"></script>
    <script src="js/contact-form-script.js"></script>
    <script src="js/custom.js"></script>
</body>
</html>

E health management system/E health management system/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>